---
- name: Create iptables directory
  file:
    path: "{{ iptables_directory }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Configure iptables ruleset
  template:
    src: iptables.j2
    dest: "{{ iptables_v4_cfg }}"
    owner: root
    group: root
    mode: 0600
  notify:
    - iptables restart